---
services:
  s3-app-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s3-app-frontend
    restart: unless-stopped
    networks: 
      - s3-app
    ports:
      - "3300:3300"
    env_file:
      - .env

  #Resources referenced from the relevant directory.
  s3-app-backend:
    build:
      context: ../s3-app-backend
      dockerfile: Dockerfile
    container_name: s3-app-backend
    restart: unless-stopped
    networks:
      - s3-app
    ports:
      - "3100:3100"
    env_file:
      - ../s3-app-backend/.env

networks:
  s3-app:
    driver: bridge
