#Deploy a production image given as an input and update the GitOps repository. 
name: Deploy to production

#Trigger the workflow on-push and manually.
on:
  workflow_dispatch:
    inputs:
      #Input for the source image tag.
      INPUT_IMAGE_TAG:
        description: "Image tag (ex- 1.5.0, 1.6.2)"
        required: true

#Global environment variables.
env:
  INPUT_IMAGE_TAG: ${{ github.event.inputs.INPUT_IMAGE_TAG }}
  PARENT_BRANCH: main
  COMMIT_USERNAME: github-actions
  COMMIT_EMAIL: github-actions@github.com
  DEPLOYMENT_REPOSITORY: Ranuldeepanayake/helm
  DEPLOYMENT_REPOSITORY_BRANCH: develop
  DEPLOYMENT_REPOSITORY_PATH: deployment-repo
  PROD_ENVIRONMENT_SOURCE_FILE: env/env-prod
  PROD_ENVIRONMENT_DESTINATION_FILE: environments/s3-app/prod/backend-env.yaml
  PROD_ENVIRONMENT_VALUES_FILE: environments/s3-app/prod/values.yaml
  DEPLOYMENT_MANIFEST_SERVICE_NAME: backend

#Permissions.
permissions:
  contents: write

jobs:
  deploy-to-production:

    runs-on: ubuntu-latest  #Runner label.
    environment: production #Environment.
    timeout-minutes: 30     #Timeout against runaway jobs.

    steps:
      #Checkout the branch which is being built.
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        ref: ${{ env.PARENT_BRANCH }}
        clean: true      #Cleans the workspace before checking out code.
        fetch-depth: 0   #Required to push back

      #Ensure jq is available. 
    - name: Install jq 
      run: sudo apt update && sudo apt install -y jq

      #Check if the image tag is in the correct format.
    - name: Validate image tag
      run: |
        echo "Input image tag: ${INPUT_IMAGE_TAG}"
        
        #Allowed patterns.
        PATTERN_1="([0-9]+\.[0-9]+\.[0]){1,1}"
        PATTERN_2="([0-9]+\.[0-9]+\.[0-9]+){1,1}"

        if [[ "${INPUT_IMAGE_TAG}" =~ $PATTERN_1 ]]; then
          echo "RELEASE image tag selected: ${INPUT_IMAGE_TAG}"
        elif [[ "${INPUT_IMAGE_TAG}" =~ $PATTERN_2 ]]; then
          echo "HOTFIX image tag selected: ${INPUT_IMAGE_TAG}"
        else
          echo "❌ invalid input image tag: ${INPUT_IMAGE_TAG}"
          exit 1          
        fi

        #Append the version number variable to the array of runtime variables.
        echo "IMAGE_TAG=${INPUT_IMAGE_TAG}" >> $GITHUB_ENV
        echo "Image tag: ${IMAGE_TAG}"

      #Checkout the gitops repository.
    - name: Checkout the deployment repository
      uses: actions/checkout@v5
      with:
        repository: ${{ env.DEPLOYMENT_REPOSITORY }}
        ref: ${{ env.DEPLOYMENT_REPOSITORY_BRANCH }}
        ssh-key: ${{ secrets.DEPLOYMENT_REPOSITORY_SSH_PRIVATE_KEY }}
        path: ${{ env.DEPLOYMENT_REPOSITORY_PATH }}
        clean: true      #Cleans the workspace before checking out code.
        fetch-depth: 0   #Required to push back

      #Checkout the main branch to get the .env file.
    - name: Checkout main branch
      run: |
        git checkout ${PARENT_BRANCH}
        echo "Selected branch: $(git branch)"

      #Copy the .env file to the deployment repository.
    - name: Copy the .env file to the deployment repository
      run: |
        cp ${PROD_ENVIRONMENT_SOURCE_FILE} ${DEPLOYMENT_REPOSITORY_PATH}/${PROD_ENVIRONMENT_DESTINATION_FILE}
        cd ${DEPLOYMENT_REPOSITORY_PATH}

        #Verify the change.
        if [[ -f "${PROD_ENVIRONMENT_DESTINATION_FILE}" ]]; then
          echo "✅ .env file exists in the destination"
        else
          echo "❌ .env file does not exist in the destination!"
          exit 1
        fi

      #Change the image tag in the deployment repository.
    - name: Update the image tag in the deployment repository
      uses: mikefarah/yq@v4.44.1
      with:
        cmd: |
          cd ${DEPLOYMENT_REPOSITORY_PATH}
          yq -i '(.containers[] | select(.name == env(DEPLOYMENT_MANIFEST_SERVICE_NAME)) | .tag) = env(IMAGE_TAG)' "${PROD_ENVIRONMENT_VALUES_FILE}"

          #Verify the change.
          TAG_READ_BACK=$(yq '.containers[] | select(.name == env(DEPLOYMENT_MANIFEST_SERVICE_NAME)) | .tag' "${PROD_ENVIRONMENT_VALUES_FILE}")
          echo "Tag read back: $TAG_READ_BACK"

          if [[ "$TAG_READ_BACK" == "${IMAGE_TAG}" ]]; then
            echo "✅ Image tag updated successfully"
          else
            echo "❌ Image tag update failed!"
            exit 1
          fi

    #Commit and push the change to the deployment repository.
    - name: Commit and push
      run: |
        cd ${DEPLOYMENT_REPOSITORY_PATH}

        git config user.name ${COMMIT_USERNAME} 
        git config user.email ${COMMIT_EMAIL}

        git add ${PROD_ENVIRONMENT_VALUES_FILE};
        git add ${PROD_ENVIRONMENT_DESTINATION_FILE};
        git commit -m "Pipeline (helm): replaced the image tag with ${IMAGE_TAG} and the .env file" || echo "No changes to commit"

        git push